### ISSUE TITLE
Add a way of creating extension packages 

### ISSUE THREAD

**Issue by damienbod** [aspnet/HealthChecks#14]
It would be nice if you could create extensions for this library so that third party extensions can be created  and used, something like hw the loggers do this. Example Data extensions packages for MySQL, PostgreSQL could be created or OPC DA, XML, UA entensions as an example.

**Comment by bradwilson** [comment]
The goal right now is to have each project under src to be a separate NuGet package. Extensions will be able to leverage `Microsoft.Extensions.HealthChecks` as the extensibility point. Please feel free to provide feedback where extensibility points should be added!
