### ISSUE TITLE
Healthcheck middleware should allow sub policy

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/HealthChecks#15]
Healthcheck middleware should be able to provide health status of specifics checks. 
For example you have 3 http endpoint check (one for web payment, one for order management & one for user management), 2 certificates (one for payment http service, one for DataProtection), 1 database for cart management, ... 
It should be possible to request health of the payment sub-system, for the order management sub-system, for the certificates, for the http endpoints, ...
```
GET /health/certificates HTTP/1.1
```
Reply
```
HTTP/1.1
[
  {
    "name": "payment certificate",
    "status": "healthy"
  },
  {
    "name": "data protection certificate",
    "status": "warning",
    "description": "Certificate is about to expire."
  }
]
```
```
GET /health/databases HTTP/1.1
```
Reply

```
HTTP/1.1
[
  {
    "name": "cart database",
    "status": "unhealthy",
    "description": "Unable to reach the database"
  }
]
```

Sub policies could be easily identified by tags on the ckecks.

**Comment by glennc** [comment]
As it stands right now the Middleware doesn't return any information. Just a status. We intend for people to accept the IHealthCheckService into a controller if they want to return more information, and then they have full control over how it renders and what configuration they have.

**Comment by ycrumeyrolle** [comment]
Agree with the fact that the middleware does not return any information.
But if I want to build a third party middleware, or to expose a custom controller, I am facing to in issue.

Imagine that I want to expose the endpoint /detailed-health/ and the endpoint /detailed-health/certificates/ 
I would like to be able to run all the checks with the first endpoint, and to run only the certificates related checks with the second endpoint. A kind of filter on the checks, not on the results.
