### ISSUE TITLE
Avoid usage of ConcurrentDictionary

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/HealthChecks#36]
In the CompositeHealthCheckResult, a Concurrent Dictionary has replaced a basic Dictionary. 
It is not necessary to be thread safe in this class if the Health Service do not add the results in different threads. 

An I wrong?
@bradwilson

**Comment by ycrumeyrolle** [comment]
In addition, you may be able to use the result of the Task.WhenAll instead of the task.Value.Result in the for each Health Service loop.

**Comment by bradwilson** [comment]
> It is not necessary to be thread safe in this class if the Health Service do not add the results in different threads.

It became necessary when parallelizing the checks (the ConcurrentDictionary is used to register the results).

> you may be able to use the result of the Task.WhenAll

If you'll notice, the loop needed to preserve both the key and the task, so you can't use the results of the Task.WhenAll, because it's waiting on the task inside the projection, but my loop needs both the key and the task.

**Comment by ycrumeyrolle** [comment]
The `CompositeHealthCheckResult.Add ()` is used within a sequential for each.
The parallel flow is execute by the Task.WhenAll just before, which is awaited.

The key used in the loop is the name of the check. The `HealthCheckResult` does not have this property, but it could be added.

**Comment by bradwilson** [comment]
I think you missed this: https://github.com/aspnet/HealthChecks/blob/93360725a04eb2270a537e41bb0b67094e39e997/src/Microsoft.Extensions.HealthChecks/Internal/UrlChecker.cs#L47

**Comment by ycrumeyrolle** [comment]
I totally missed it.
I am not sure that current implementation of http check is mature. 
Http check will probably require authentication specific for each endpoint, and may be a custom validation extension point, because some endpoint returns 200 even in case of errors, or some endpoint returns 500 or 400 even if not in error.
Why allowing multicheck within this check and not in the others?  If if is for a simpler registration, this can be done with a builder provider multiple checkers instead of a single multichecker.

When I look at the `UrlChecker` implementation,  is see a lot of similitude to the `HealthCheckService`. I though that the check flow were managed by the service,  but it is also managed by the checkers. You are what I mean?

**Comment by bradwilson** [comment]
The role of multi-checks within UrlChecker may change depending on whether we choose to support grouping (see #16). Generalized grouping would alleviate the need to UrlCheck vs. UrlChecks. /cc @glennc
