### ISSUE TITLE
Have builds of this repo go to a nightly feed

### ISSUE THREAD

**Issue by Eilon** [aspnet/HealthChecks#7]
* Add the build stuff to this repo for automated builds
* Add stuff like NuGet Package Verifier
* Code signing

**Comment by svantreeck** [comment]
Are there plans to put this in nuget?  I see it got cut from the 2.0.0 release 👎

**Comment by CESARDELATORRE** [comment]
@svantreeck Intially, putting the HealthChecks library plus other patterns-libs into ASP.NET Core will probably happen in the .NET Core 2.1 wave. But this is NOT a promise. ;)

**Comment by pmareke** [comment]
@CESARDELATORRE Hi Cesar, finally with the release of the 2.1 version is it include? Thanks for your work!

**Comment by ghost** [comment]
Like @pmareke i need to know the the next planning.

**Comment by CESARDELATORRE** [comment]
@pmareke - Nope, sorry, it is not coming in .NET Core 2.1.
Adding @glennc who's the owner of this feature. Hopefully it'll come in a future version.

**Comment by li0nsar3c00l** [comment]
Any chance we can get a preview nuget package any time soon? Merging or adapting #66 would be really nice, cause waiting for Q4 for an official integration into .NET Core 2.2 is quite a while...

**Comment by JuergenGutsch** [comment]
The API of the 2.2 version of the HealthChecks may change a lot. It is not sure that they moved exactly this codes to ASP.NET Core 2.2. Take a look into the ASP.NET Core repo.
With this in mind, it doesn't really make sense to put this into a NuGet package.
On the other hand, I like this version, as well and I also put some effort in it. Maybe it makes sens to forq this repo, make it stable and create shippable bits out of it. ;-)

**Comment by Eilon** [comment]
Closing because this is replaced by https://github.com/aspnet/Diagnostics/tree/release/2.2/src.
