### ISSUE TITLE
Already implemented in an Open Source project

### ISSUE THREAD

**Issue by alhardy** [aspnet/HealthChecks#8]
Looks like this come from a [Metrics.Net](https://github.com/etishor/Metrics.NET) [extension](https://github.com/alhardy/aspnet-metrics/blob/dev/src/AspNet.Metrics/DependencyInjection/MetricsCoreBuilderExtensions.cs#L17) written for dotnet core.

My implementation written a while back [looks very similar](https://alhardy.github.io/app-metrics-docs/getting-started/health-checks/index.html#configuring-health-checks), feel as though my efforts in open sourcing will be wasted :(

[Here's the Repo](https://github.com/alhardy/AppMetrics/tree/1.0.0)

**Comment by Eilon** [comment]
Hi @alhardy this looks like it's a coincidence because the two projects are in very similar areas, so some types and members have similar names. All the contributions to the repo here are original.

**Comment by glennc** [comment]
@alhardy This library is purely a way to define a set of functions that you can run to determine the health of your application, with the associated middleware and other pieces to allow it to work with ASP.NET and ASP.NET Core. AppMetrics appears to be significantly more than that.

Happy to work with you on defining what the IHealthCheckResult, IHealthCheck and IHealthCheckService interfaces should look like and discuss the ability to smoothly switch between this and your efforts.

**Comment by alhardy** [comment]
@Eilon Not saying otherwise, just pointing out that there is already pretty much the same implementation.

@glennc Cheers, I'll try plugging in this implementation instead of mine a little down the track.
