### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Kukks** [aspnet/HealthChecks#82]
There are multiple open PRs with great new useful features dating back months. Has this project been abandoned?

**Comment by JuergenGutsch** [comment]
Maybe and hopefully it is not dead. It seems to go to the 2.2 release

See the latest "ASP.NET Community Standup - April 24, 2018 - Super Early ASP.NET Core 2.2 Feature Planning:" 
https://youtu.be/k0Xy-5zE9to?t=52m40s

**Comment by Kukks** [comment]
Seems like you have a number of PRs pending here @JuergenGutsch. Do you have a branch with all the PRs combined? ;)

**Comment by JuergenGutsch** [comment]
Yes, it seems so :-) 
I actually was involved at the beginning of that project in November 2016 during the MVP Summit. That's why I keep an eye on it and would be really happy and kinda proud if this thing gets released.

I usually create a separate branch per issue on my fork and create a PR out of that branch.

**Comment by glennc** [comment]
We intend to finish and ship a HealthChecks library, and this should be thought of as an experiment that helped us choose a course. It will probably not be exactly this code that goes but rather a new repo in the aspnet org that's inspired by and learns from this one.

That's what I expect anyway. The goals are still the same, it's just taking us a long time to finally get it close enough to the top of the priority list that we actually do it.

**Comment by glennc** [comment]
We didn't start out with that as a goal, but I think that's what it has turned into.

**Comment by HelloKitty** [comment]
Might want to update [this docs page](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health) then since it still points people here as a "Early release".

**Comment by CESARDELATORRE** [comment]
I just create a PR clarifying that point. In any case, it was an early release of that library. It didn't say it was an early release of any official part of ASP.NET Core. But agree, it is better to clarify that point. 👍 
https://github.com/dotnet/docs/pull/5124 
Closing this issue as I hope the question is clarified now. :)
